In [1]:
import numpy as np
import pandas as pd
import gc
import time

from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split

from tqdm import tqdm

import warnings
from time import time

In [2]:
%%time
train = pd.read_csv('../../TPS_2021/input/tabular-playground-series-sep-2021/train.csv')
test = pd.read_csv('../../TPS_2021/input/tabular-playground-series-sep-2021/test.csv')

CPU times: user 11.6 s, sys: 631 ms, total: 12.2 s
Wall time: 12.2 s

In [3]:
train.head()

,id,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f110,f111,f112,f113,f114,f115,f116,f117,f118,claim
0,0,0.10859,0.004314,-37.566,0.017364,0.28915,-10.25100,135.12,168900.0,3.992400e+14,...,-12.2280,1.7482,1.90960,-7.11570,4378.80,1.2096,8.613400e+14,140.1,1.01770,1
1,1,0.10090,0.299610,11822.000,0.276500,0.45970,-0.83733,1721.90,119810.0,3.874100e+15,...,-56.7580,4.1684,0.34808,4.14200,913.23,1.2464,7.575100e+15,1861.0,0.28359,0
2,2,0.17803,-0.006980,907.270,0.272140,0.45948,0.17327,2298.00,360650.0,1.224500e+13,...,-5.7688,1.2042,0.26290,8.13120,45119.00,1.1764,3.218100e+14,3838.2,0.40690,1
3,3,0.15236,0.007259,780.100,0.025179,0.51947,7.49140,112.51,259490.0,7.781400e+13,...,-34.8580,2.0694,0.79631,-16.33600,4952.40,1.1784,4.533000e+12,4889.1,0.51486,1
4,4,0.11623,0.502900,-109.150,0.297910,0.34490,-0.40932,2538.90,65332.0,1.907200e+15,...,-13.6410,1.5298,1.14640,-0.43124,3856.50,1.4830,-8.991300e+12,NaN,0.23049,1

In [4]:
features = train.columns[1:-1]

In [6]:
target = train[['claim']].values
train.drop(['claim', 'id'], axis=1, inplace=True)
test.drop(['id', ], axis=1, inplace=True)

In [7]:
%%time
train_test = pd.concat([train, test], axis =0)
RS = RobustScaler()
RS.fit(train_test)
del train_test
gc.collect()
gc.collect()
train[features] = RS.transform(train)
test[features] = RS.transform(test)
del RS
gc.collect()
gc.collect()

CPU times: user 11.1 s, sys: 6.78 s, total: 17.9 s
Wall time: 17.9 s

0

In [8]:
train.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f109,f110,f111,f112,f113,f114,f115,f116,f117,f118
0,0.398513,-2.196735,-0.327562,-0.457117,-0.224705,-4.832408,-0.650800,-0.257438,-0.034024,-0.176089,...,-0.485974,0.101992,0.082891,0.009230,-0.707561,-0.175480,0.339979,-0.236289,-0.639046,1.159886
1,0.232340,-0.510677,2.623548,0.531940,0.765310,-0.223828,0.137755,-0.362114,1.089490,1.580351,...,1.211240,-1.799098,2.421022,-0.070401,0.287003,-0.215791,0.726128,-0.108588,-0.283260,-0.404939
2,1.899043,-2.261220,-0.092451,0.515299,0.764033,0.270924,0.424050,0.151439,-0.159149,2.625873,...,-0.309372,0.377750,-0.442663,-0.074745,0.639430,0.298402,-0.008395,-0.246551,0.125514,-0.142092
3,1.344340,-2.179918,-0.124095,-0.427289,1.112266,3.853606,-0.662036,-0.064269,-0.137949,-0.198042,...,-0.726599,-0.864136,0.393199,-0.047543,-1.522131,-0.168808,0.012592,-0.252586,0.342782,0.088035
4,0.563606,0.650051,-0.345375,0.613657,0.098914,-0.014290,0.543766,-0.478280,0.453539,-0.165830,...,1.114520,0.041668,-0.128104,-0.029690,-0.117021,-0.181555,3.208814,-0.252843,NaN,-0.518127

In [9]:
xgtrain, xgval, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=42)

In [10]:
xgtrain['target'] = y_train
xgval['target'] = y_val

In [11]:
xgtrain.to_csv('../../TPS_2021/input/tabular-playground-series-sep-2021/xgtrain.csv', index=False)
xgval.to_csv('../../TPS_2021/input/tabular-playground-series-sep-2021/xgval.csv', index=False)